name: Validación HTML y Enlaces

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v3
    
    - name: Validar HTML5
      run: |
        sudo apt-get update
        sudo apt-get install -y tidy
        echo "Validando archivos HTML..."
        for file in *.html; do
          echo "Validando $file"
          tidy -q -e -utf8 "$file" || echo "Advertencias en $file"
        done
    
    - name: Verificar enlaces externos
      run: |
        echo "Verificando APIs de NASA GIBS..."
        curl -f -s -I "https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2024-01-01/GoogleMapsCompatible_Level9/3/4/2.jpg" || exit 1
        echo "✓ API MODIS funciona"
        
        echo "Verificando Leaflet CDN..."
        curl -f -s -I "https://unpkg.com/leaflet/dist/leaflet.css" || exit 1
        echo "✓ Leaflet CDN funciona"
        
        echo "Verificando OpenStreetMap..."
        curl -f -s -I "https://tile.openstreetmap.org/0/0/0.png" || exit 1
        echo "✓ OpenStreetMap funciona"
    
    - name: Verificar sintaxis JavaScript
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Resultado
      run: |
        echo "✅ Validación completada exitosamente"
        echo "El código está listo para desplegarse"